#!/usr/bin/env bash

# defaults
__url="https://api.mail.tm"
__tmp="/tmp/bail-domain.$$.tmp"

# cleanup
trap 'rm -f "$__tmp"*' EXIT

curl -s "$__url/domains" >"$__tmp" || exit 1
__domain=$(jq -r '."hydra:member"[0].domain' "$__tmp")

if [[ -n "$__domain" && "$__domain" != "null" ]]; then
    if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
        printf '%s\n' "$__domain"
    fi
else
    printf "error: no domain found\n" >&2
    exit 1
fi
