#!/usr/bin/env bash

__url="https://api.mail.tm"
__cache="${XDG_STATE_HOME:-$HOME/.config/state}/bail"
__acc="$__cache/account"
__tmp="/tmp/bail-create.$$.tmp"
__v="0.5"

if [[ "$1" == "-h" || "$1" == "--help" || "$1" == "help" ]]; then
	printf 'bail-create v%s\n' "$__v"
	printf 'usage: bail-create [prefix] [-p password]\n\n'
	printf 'provision a new mail account. deletes previous account if present.\n\n'
	printf 'arguments:\n'
	printf '  prefix          custom email prefix (default: user_RANDOM)\n\n'
	printf 'options:\n'
	printf '  -p password     specify a custom account password\n'
	printf '  -h, --help      show this help message\n'
	printf '  -v, --version   show version information\n\n'
	printf 'examples:\n'
	printf '  bail create\n'
	printf '  bail create myname\n'
	printf '  bail create myname -p mypassword\n'
	exit 0
fi

if [[ "$1" == "-v" || "$1" == "--version" ]]; then
	printf 'bail-create v%s\n' "$__v"
	exit 0
fi

trap 'rm -f "$__tmp"*' EXIT

if [[ ! -d "$__cache" ]]; then
	mkdir -p "$__cache" || exit 1
fi

if [[ -s "$__acc" ]]; then
	"${0%/*}/bail-delete" -y >/dev/null 2>&1
fi

password=''
custom=0
prefix=''

while [[ $# -gt 0 ]]; do
	case "$1" in
	-p)
		shift
		password="$1"
		custom=1
		;;
	*)
		prefix="$1"
		;;
	esac
	shift
done

[[ "$custom" -eq 1 ]] || password="p_${RANDOM}${RANDOM}"

. "${0%/*}/bail-domain"
domain="$__domain"

if [[ -n "$prefix" ]]; then
	address="$prefix@$domain"
else
	address="user_${RANDOM}@$domain"
fi

printf '{"address":"%s","password":"%s"}' "$address" "$password" >"$__tmp.data"
curl -s "$__url/accounts" \
	-H 'Content-Type: application/json' \
	-d @"$__tmp.data" >"$__tmp.resp"

if [[ $? -ne 0 ]]; then
	printf "error: account creation failed\n" >&2
	exit 1
fi

jq --arg pw "$password" '. + {password: $pw}' "$__tmp.resp" >"$__acc"
if [[ $? -ne 0 ]]; then
	printf "error: failed to save account data\n" >&2
	exit 1
fi

printf 'created\n'
printf 'address: %s\n' "$address"
printf 'password: %s\n' "$password"
